# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from nvmidl.apps.fed_learn.protos import federated_pb2 as nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2


class FederatedTrainingStub(object):
  """The global federated model interfaces
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/fedlearn.FederatedTraining/Register',
        request_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientLogin.SerializeToString,
        response_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.FromString,
        )
    self.Quit = channel.unary_unary(
        '/fedlearn.FederatedTraining/Quit',
        request_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientState.SerializeToString,
        response_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.FromString,
        )
    self.GetModel = channel.unary_unary(
        '/fedlearn.FederatedTraining/GetModel',
        request_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientState.SerializeToString,
        response_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.CurrentModel.FromString,
        )
    self.SubmitUpdate = channel.unary_unary(
        '/fedlearn.FederatedTraining/SubmitUpdate',
        request_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.Contribution.SerializeToString,
        response_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/fedlearn.FederatedTraining/Heartbeat',
        request_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.Token.SerializeToString,
        response_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.FromString,
        )


class FederatedTrainingServicer(object):
  """The global federated model interfaces
  """

  def Register(self, request, context):
    """client registration, so that it will contribute to the training
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Quit(self, request, context):
    """client quiting the federated training
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModel(self, request, context):
    """server to client model sharing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitUpdate(self, request, context):
    """client to server contribution submission
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    """client to server heartbeat keep live
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FederatedTrainingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientLogin.FromString,
          response_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.SerializeToString,
      ),
      'Quit': grpc.unary_unary_rpc_method_handler(
          servicer.Quit,
          request_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientState.FromString,
          response_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.SerializeToString,
      ),
      'GetModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetModel,
          request_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.ClientState.FromString,
          response_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.CurrentModel.SerializeToString,
      ),
      'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitUpdate,
          request_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.Contribution.FromString,
          response_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.Token.FromString,
          response_serializer=nvmidl_dot_apps_dot_fed__learn_dot_protos_dot_federated__pb2.FederatedSummary.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fedlearn.FederatedTraining', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
